// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo65-yEiuHEXSHlJegD5Q-xPTbU6vzbYg',
    appId: '1:235788135367:android:863e215d3d74446b4c87e2',
    messagingSenderId: '235788135367',
    projectId: 'tandrustito-b76da',
    databaseURL: 'https://tandrustito-b76da-default-rtdb.firebaseio.com',
    storageBucket: 'tandrustito-b76da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUm3T9LaXayAnNgO5y8PLrv68jHH_qV8U',
    appId: '1:235788135367:ios:0c97bd5462996ff74c87e2',
    messagingSenderId: '235788135367',
    projectId: 'tandrustito-b76da',
    databaseURL: 'https://tandrustito-b76da-default-rtdb.firebaseio.com',
    storageBucket: 'tandrustito-b76da.appspot.com',
    iosClientId: '235788135367-e7rlnp9nc7jnmahgo42gjk976oio8urm.apps.googleusercontent.com',
    iosBundleId: 'com.mod.tandrwstito.app',
  );
}
